# out_dir: "results"

data:
  deskew: True
  preprocess: True
  max_range: 100.0 # can be also changed in the CLI
  min_range: 0.0

mapping:
  voxel_size: 1.0 # <- optional
  max_points_per_voxel: 20

adaptive_threshold:
  fixed_threshold: 0.3 # <- optional, disables adaptive threshold
  # initial_threshold: 2.0
  # min_motion_th: 0.1